# Generated by Django 4.1.1 on 2022-10-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dockermon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_per", models.CharField(max_length=50)),
                ("mem_per", models.CharField(max_length=50)),
                ("disk_per", models.CharField(max_length=50)),
            ],
        ),
    ]
